export const categories = [
  "Classic Tea Series",
  "Milk Tea Series",
  "Fresh Milk Series",
  "Fruit Tea Series",
  "Mojito Series",
  "Specialty Drinks",
  "Toppings",
]

export const menuItems = {
  "Classic Tea Series": [
    {
      id: 1,
      name: "Black Tea",
      description: "Traditional Ceylon black tea, bold and full-bodied with a rich amber color and robust flavor",
      price: 22000,
      image: "/placeholder.svg",
      category: "Classic Tea Series",
    },
    {
      id: 2,
      name: "Green Tea",
      description: "Light and refreshing Chinese green tea with a delicate, slightly sweet finish",
      price: 22000,
      image: "/placeholder.svg",
      category: "Classic Tea Series",
    },
    {
      id: 3,
      name: "Oolong Tea",
      description: "Semi-oxidized tea with a smooth, floral flavor and subtle fruity notes",
      price: 24000,
      image: "/placeholder.svg",
      category: "Classic Tea Series",
    },
    {
      id: 4,
      name: "Jasmine Green Tea",
      description: "Green tea naturally scented with jasmine flowers, offering a fragrant and soothing experience",
      price: 22000,
      image: "/placeholder.svg",
      category: "Classic Tea Series",
    },
    {
      id: 5,
      name: "Earl Grey Tea",
      description: "Premium black tea flavored with bergamot oil, creating a distinctive citrusy aroma",
      price: 24000,
      image: "/placeholder.svg",
      category: "Classic Tea Series",
    },
  ],
  "Milk Tea Series": [
    {
      id: 6,
      name: "Classic Pearl Milk Tea",
      description: "Black tea blended with creamy milk and chewy tapioca pearls, the signature bubble tea experience",
      price: 28000,
      image: "/placeholder.svg",
      category: "Milk Tea Series",
    },
    {
      id: 7,
      name: "Thai Tea",
      description:
        "Strong black tea blend with creamy milk and aromatic spices, creating a rich orange-colored beverage",
      price: 30000,
      image: "/placeholder.svg",
      category: "Milk Tea Series",
    },
    {
      id: 8,
      name: "Wintermelon Milk Tea",
      description: "Milk tea infused with sweet wintermelon flavor, offering a unique and refreshing taste",
      price: 32000,
      image: "/placeholder.svg",
      category: "Milk Tea Series",
    },
    {
      id: 9,
      name: "Okinawa Pearl Milk Tea",
      description: "Brown sugar milk tea with roasted notes and a caramel-like sweetness",
      price: 34000,
      image: "/placeholder.svg",
      category: "Milk Tea Series",
    },
    {
      id: 10,
      name: "Taro Pearl Milk Tea",
      description: "Creamy taro root flavor with milk tea and pearls, producing a naturally purple-tinted drink",
      price: 34000,
      image: "/placeholder.svg",
      category: "Milk Tea Series",
    },
  ],
  "Fresh Milk Series": [
    {
      id: 11,
      name: "Fresh Milk with Pearl",
      description: "Pure, cold fresh milk served with bouncy tapioca pearls",
      price: 30000,
      image: "/placeholder.svg",
      category: "Fresh Milk Series",
    },
    {
      id: 12,
      name: "Fresh Milk with Red Bean",
      description: "Fresh milk paired with sweet, tender red bean paste",
      price: 32000,
      image: "/placeholder.svg",
      category: "Fresh Milk Series",
    },
    {
      id: 13,
      name: "Fresh Milk with Grass Jelly",
      description: "Fresh milk with herbal grass jelly, offering a subtle sweetness and unique texture",
      price: 32000,
      image: "/placeholder.svg",
      category: "Fresh Milk Series",
    },
    {
      id: 14,
      name: "Fresh Taro Milk",
      description: "Fresh milk blended with real taro root, creating a naturally sweet, nutty flavor",
      price: 34000,
      image: "/placeholder.svg",
      category: "Fresh Milk Series",
    },
  ],
  "Fruit Tea Series": [
    {
      id: 15,
      name: "Passion Fruit Tea",
      description: "Green tea with tropical passion fruit, delivering a tangy and refreshing taste",
      price: 28000,
      image: "/placeholder.svg",
      category: "Fruit Tea Series",
    },
    {
      id: 16,
      name: "Peach Tea",
      description: "Black tea with sweet peach flavor, perfect balance of fruit and tea",
      price: 28000,
      image: "/placeholder.svg",
      category: "Fruit Tea Series",
    },
    {
      id: 17,
      name: "Mango Green Tea",
      description: "Green tea with fresh mango, creating a tropical paradise in a cup",
      price: 30000,
      image: "/placeholder.svg",
      category: "Fruit Tea Series",
    },
    {
      id: 18,
      name: "Lychee Tea",
      description: "Black tea with sweet lychee fruit, offering a delicate floral sweetness",
      price: 28000,
      image: "/placeholder.svg",
      category: "Fruit Tea Series",
    },
    {
      id: 19,
      name: "Strawberry Tea",
      description: "Green tea with fresh strawberry flavor, providing a fruity and refreshing experience",
      price: 28000,
      image: "/placeholder.svg",
      category: "Fruit Tea Series",
    },
  ],
  "Mojito Series": [
    {
      id: 20,
      name: "Classic Mojito",
      description: "Lime, mint, and tea blend, a refreshing non-alcoholic twist on the classic cocktail",
      price: 32000,
      image: "/placeholder.svg",
      category: "Mojito Series",
    },
    {
      id: 21,
      name: "Passion Fruit Mojito",
      description: "Tropical passion fruit with mint and lime, creating an exotic refreshment",
      price: 34000,
      image: "/placeholder.svg",
      category: "Mojito Series",
    },
    {
      id: 22,
      name: "Lemon Mojito",
      description: "Fresh lemon with mint, offering a bright and invigorating taste",
      price: 32000,
      image: "/placeholder.svg",
      category: "Mojito Series",
    },
    {
      id: 23,
      name: "Peach Mojito",
      description: "Sweet peach with mint and lime, delivering a unique fruity combination",
      price: 34000,
      image: "/placeholder.svg",
      category: "Mojito Series",
    },
  ],
  "Specialty Drinks": [
    {
      id: 24,
      name: "Brown Rice Green Milk Tea",
      description: "Green tea with roasted brown rice notes, offering a nutty, toasted flavor",
      price: 36000,
      image: "/placeholder.svg",
      category: "Specialty Drinks",
    },
    {
      id: 25,
      name: "Matcha Red Bean Milk Tea",
      description: "Premium Japanese green tea powder with red bean, creating a rich, traditional flavor",
      price: 38000,
      image: "/placeholder.svg",
      category: "Specialty Drinks",
    },
    {
      id: 26,
      name: "Tiger Milk Tea",
      description: "Brown sugar streaks with milk tea and pearls, creating a visually striking drink",
      price: 38000,
      image: "/placeholder.svg",
      category: "Specialty Drinks",
    },
    {
      id: 27,
      name: "Hokkaido Milk Tea",
      description: "Rich and creamy milk tea with caramel notes, inspired by Japanese milk tea",
      price: 36000,
      image: "/placeholder.svg",
      category: "Specialty Drinks",
    },
  ],
  Toppings: [
    {
      id: 28,
      name: "Boba/Pearls",
      description: "Chewy tapioca balls with a soft, bouncy texture",
      price: 5000,
      image: "/placeholder.svg",
      category: "Toppings",
    },
    {
      id: 29,
      name: "Pudding",
      description: "Smooth egg custard with a silky texture",
      price: 6000,
      image: "/placeholder.svg",
      category: "Toppings",
    },
    {
      id: 30,
      name: "Red Bean",
      description: "Sweet Asian red beans, cooked to tender perfection",
      price: 6000,
      image: "/placeholder.svg",
      category: "Toppings",
    },
    {
      id: 31,
      name: "Grass Jelly",
      description: "Herbal jelly with a subtle sweet flavor and unique texture",
      price: 5000,
      image: "/placeholder.svg",
      category: "Toppings",
    },
    {
      id: 32,
      name: "Crystal Boba",
      description: "Clear, chewy tapioca pearls with a lighter texture than traditional boba",
      price: 6000,
      image: "/placeholder.svg",
      category: "Toppings",
    },
    {
      id: 33,
      name: "Egg Pudding",
      description: "Rich custard pudding with a smooth, creamy consistency",
      price: 7000,
      image: "/placeholder.svg",
      category: "Toppings",
    },
    {
      id: 34,
      name: "Aloe Vera",
      description: "Sweet, clear aloe jelly with a refreshing crunch",
      price: 6000,
      image: "/placeholder.svg",
      category: "Toppings",
    },
    {
      id: 35,
      name: "Coconut Jelly",
      description: "Soft, sweet coconut-flavored jelly pieces",
      price: 5000,
      image: "/placeholder.svg",
      category: "Toppings",
    },
  ],
}

