import { NextResponse } from "next/server";

// This is a mock API endpoint that returns the restaurant data
// In a real application, this would fetch data from your backend
export async function GET() {
  // Simulating API response delay
  await new Promise((resolve) => setTimeout(resolve, 500));

  return NextResponse.json({
    data: {
      name: "Sharetea",
      location: "Mal Taman Anggrek",
      latitude: -6.1773405931255,
      longitude: 106.79128929521,
      image:
        "http://34.81.222.105/v1/storage/buckets/673950ca001e44cd0d28/files/67c480fd000008a2700c/view?project=679f99e00018a0a10d4a",
      logo: "https://franchise.sharetea.com.au/wp-content/uploads/2021/08/cropped-Favicon.png",
      tag: "u50k",
      pointValue: 20000,
      busyMode: "normal",
      normalWaitTime: 15,
      rushWaitTime: 25,
      emoji: "🧋",
      isOpen: true,
      phoneNumber: "+6281234567890",
      pickupInstructions: null,
      googleMapsUrl: null,
      waitTime: 5,
      address: "Jalan Share Tea",
      timezone: "Asia/Jakarta",
      $id: "675c6c400035d189ce4a",
      openingTimes: {
        MON: [
          {
            openTime: "2025-03-06T03:00:01.437+00:00",
            closeTime: "2025-03-06T14:00:01.446+00:00",
          },
        ],
        TUE: [
          {
            openTime: "2025-03-06T02:00:01.446+00:00",
            closeTime: "2025-03-06T14:00:01.446+00:00",
          },
        ],
        WED: [
          {
            openTime: "2025-03-06T02:00:01.446+00:00",
            closeTime: "2025-03-06T14:00:01.446+00:00",
          },
        ],
        THU: [
          {
            openTime: "2025-03-06T02:00:01.446+00:00",
            closeTime: "2025-03-06T14:00:01.446+00:00",
          },
        ],
        FRI: [
          {
            openTime: "2025-03-06T02:00:01.446+00:00",
            closeTime: "2025-03-06T14:00:01.446+00:00",
          },
        ],
        SAT: [
          {
            openTime: "2025-03-06T02:00:01.446+00:00",
            closeTime: "2025-03-06T14:00:01.446+00:00",
          },
        ],
        SUN: [
          {
            openTime: "2025-03-06T02:00:01.446+00:00",
            closeTime: "2025-03-06T14:00:01.446+00:00",
          },
        ],
      },
      menuCategoryId: [
        {
          name: "Milk Tea Series",
          index: null,
          $id: "67a92a4300362267e308",
          menuId: [
            {
              name: "Taro Milk Tea",
              description: "Teh susu taro dengan rasa manis dan krimi",
              price: 23000,
              image:
                "https://fullofplants.com/wp-content/uploads/2022/03/creamy-vegan-taro-milk-tea-with-boba-thumb-2.jpg",
              isRecommended: true,
              isInStock: true,
              sku: null,
              pointPrice: null,
              outstock: null,
              $id: "675c70af0032535de5a0",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
                {
                  name: "Toppings",
                  isRequired: false,
                  maxAmount: 3,
                  type: "checkbox",
                  minAmount: 0,
                  $id: "675c6e8900418bc56f34",
                  menuOptionId: [
                    {
                      name: "Boba",
                      description: "Chewy tapioca pearls",
                      price: 5000,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e89004190cd8a12",
                    },
                    {
                      name: "Grass Jelly",
                      description: "Sweet herbal jelly",
                      price: 5000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e8900419f3d9c45",
                    },
                    {
                      name: "Pudding",
                      description: "Smooth egg pudding",
                      price: 6000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e890041a2e5d378",
                    },
                    {
                      name: "Aloe Vera",
                      description: "Sweet aloe cubes",
                      price: 6000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e890041b1f4e289",
                    },
                  ],
                },
              ],
            },
            {
              name: "Matcha Milk Tea",
              description: "Teh susu matcha segar dan kaya rasa",
              price: 26000,
              image:
                "https://www.texanerin.com/content/uploads/2023/05/matcha-with-boba-image-1200.jpg",
              isRecommended: false,
              isInStock: true,
              sku: null,
              pointPrice: null,
              outstock: null,
              $id: "675c70c80008c3cb0aa5",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
                {
                  name: "Toppings",
                  isRequired: false,
                  maxAmount: 3,
                  type: "checkbox",
                  minAmount: 0,
                  $id: "675c6e8900418bc56f34",
                  menuOptionId: [
                    {
                      name: "Boba",
                      description: "Chewy tapioca pearls",
                      price: 5000,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e89004190cd8a12",
                    },
                    {
                      name: "Grass Jelly",
                      description: "Sweet herbal jelly",
                      price: 5000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e8900419f3d9c45",
                    },
                    {
                      name: "Pudding",
                      description: "Smooth egg pudding",
                      price: 6000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e890041a2e5d378",
                    },
                    {
                      name: "Aloe Vera",
                      description: "Sweet aloe cubes",
                      price: 6000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e890041b1f4e289",
                    },
                  ],
                },
              ],
            },
            {
              name: "Brown Sugar Milk Tea",
              description: "Teh susu dengan sirup gula merah yang kaya",
              price: 28000,
              image:
                "https://takestwoeggs.com/wp-content/uploads/2021/04/Brown-Sugar-Milk-Tea-Boba-Recipe-Takestwoeggs-Easy-Asian-Inspired-Recipes-sq.jpg",
              isRecommended: true,
              isInStock: true,
              sku: null,
              pointPrice: 6,
              outstock: null,
              $id: "675c72c10051a3e1f239",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Toppings",
                  isRequired: false,
                  maxAmount: 3,
                  type: "checkbox",
                  minAmount: 0,
                  $id: "675c6e8900418bc56f34",
                  menuOptionId: [
                    {
                      name: "Boba",
                      description: "Chewy tapioca pearls",
                      price: 5000,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e89004190cd8a12",
                    },
                    {
                      name: "Grass Jelly",
                      description: "Sweet herbal jelly",
                      price: 5000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e8900419f3d9c45",
                    },
                    {
                      name: "Pudding",
                      description: "Smooth egg pudding",
                      price: 6000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e890041a2e5d378",
                    },
                    {
                      name: "Aloe Vera",
                      description: "Sweet aloe cubes",
                      price: 6000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e890041b1f4e289",
                    },
                  ],
                },
              ],
            },
            {
              name: "Hokkaido Milk Tea",
              description: "Teh susu krim dengan rasa karamel yang lembut",
              price: 25000,
              image:
                "https://sugaryums.com/wp-content/uploads/2022/02/Hokkaido-Milk-Tea-SugarYums-6.jpg",
              isRecommended: false,
              isInStock: true,
              sku: null,
              pointPrice: null,
              outstock: null,
              $id: "675c72d10058a4f2g451",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
                {
                  name: "Toppings",
                  isRequired: false,
                  maxAmount: 3,
                  type: "checkbox",
                  minAmount: 0,
                  $id: "675c6e8900418bc56f34",
                  menuOptionId: [
                    {
                      name: "Boba",
                      description: "Chewy tapioca pearls",
                      price: 5000,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e89004190cd8a12",
                    },
                    {
                      name: "Grass Jelly",
                      description: "Sweet herbal jelly",
                      price: 5000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e8900419f3d9c45",
                    },
                    {
                      name: "Pudding",
                      description: "Smooth egg pudding",
                      price: 6000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e890041a2e5d378",
                    },
                    {
                      name: "Aloe Vera",
                      description: "Sweet aloe cubes",
                      price: 6000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e890041b1f4e289",
                    },
                  ],
                },
              ],
            },
            {
              name: "Strawberry Milk Tea",
              description: "Teh susu dengan rasa stroberi yang menyegarkan",
              price: 24000,
              image:
                "https://myveganminimalist.com/wp-content/uploads/2022/04/Strawberry-Milk-Tea-Boba-20.jpg",
              isRecommended: true,
              isInStock: true,
              sku: null,
              pointPrice: 5,
              outstock: null,
              $id: "675c72e10062a3e4g125",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
                {
                  name: "Toppings",
                  isRequired: false,
                  maxAmount: 3,
                  type: "checkbox",
                  minAmount: 0,
                  $id: "675c6e8900418bc56f34",
                  menuOptionId: [
                    {
                      name: "Boba",
                      description: "Chewy tapioca pearls",
                      price: 5000,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e89004190cd8a12",
                    },
                    {
                      name: "Grass Jelly",
                      description: "Sweet herbal jelly",
                      price: 5000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e8900419f3d9c45",
                    },
                    {
                      name: "Pudding",
                      description: "Smooth egg pudding",
                      price: 6000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e890041a2e5d378",
                    },
                    {
                      name: "Aloe Vera",
                      description: "Sweet aloe cubes",
                      price: 6000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e890041b1f4e289",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Classic Tea Series",
          index: null,
          $id: "67affa87000121b38a72",
          menuId: [
            {
              name: "Honey Milk Tea",
              description: "Teh susu dengan sentuhan madu yang manis",
              price: 22000,
              image:
                "https://131248217.cdn6.editmysite.com/uploads/1/3/1/2/131248217/s478381384635632615_p51_i1_w1920.jpeg",
              isRecommended: true,
              isInStock: true,
              sku: null,
              pointPrice: 5,
              outstock: null,
              $id: "675c710100161a692557",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
              ],
            },
            {
              name: "Chocolate Milk Tea",
              description: "Teh susu cokelat yang lezat dan nikmat",
              price: 21000,
              image:
                "https://entirelyelizabeth.com/wp-content/uploads/2022/11/IMG_1811-2.jpg",
              isRecommended: false,
              isInStock: true,
              sku: null,
              pointPrice: null,
              outstock: null,
              $id: "675c714b00287279a3af",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
              ],
            },
            {
              name: "Jasmine Green Tea",
              description: "Teh hijau jasmine klasik yang menyegarkan",
              price: 19000,
              image: null,
              isRecommended: false,
              isInStock: true,
              sku: null,
              pointPrice: 4,
              outstock: null,
              $id: "675c714f0029a5e3b4cd",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
              ],
            },
            {
              name: "Oolong Tea",
              description: "Teh Oolong klasik dengan rasa yang khas",
              price: 20000,
              image: null,
              isRecommended: true,
              isInStock: true,
              sku: null,
              pointPrice: null,
              outstock: null,
              $id: "675c7151002aa6f4c5de",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
              ],
            },
            {
              name: "Earl Grey Tea",
              description: "Teh hitam Earl Grey dengan aroma bergamot",
              price: 20000,
              image: null,
              isRecommended: false,
              isInStock: true,
              sku: null,
              pointPrice: null,
              outstock: null,
              $id: "675c7153002ba7g5d6ef",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "Fruit Tea Series",
          index: null,
          $id: "67affb92000232c49b83",
          menuId: [
            {
              name: "Lychee Tea",
              description: "Teh hitam dengan rasa leci yang manis dan segar",
              price: 24000,
              image:
                "https://cdn.foodaciously.com/static/recipes/6a8cad49-6315-416d-995f-9c6861996228/lychee-iced-tea-b5557cf2e58ecc5f0615a1812e98bc0b-1920-q80.jpg",
              isRecommended: true,
              isInStock: true,
              sku: null,
              pointPrice: null,
              outstock: null,
              $id: "675c7155002cb8h6e7fg",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
                {
                  name: "Fruit Popping",
                  isRequired: false,
                  maxAmount: 2,
                  type: "checkbox",
                  minAmount: 0,
                  $id: "675c6e9000419cd67g45",
                  menuOptionId: [
                    {
                      name: "Lychee Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e9000420de78h56",
                    },
                    {
                      name: "Strawberry Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e9000421ef89i67",
                    },
                    {
                      name: "Mango Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e9000422fg90j78",
                    },
                  ],
                },
              ],
            },
            {
              name: "Peach Tea",
              description: "Teh hitam dengan rasa persik yang segar",
              price: 24000,
              image:
                "https://www.vegetarianventures.com/wp-content/uploads/2019/07/PeachLemonadeBlog-16-of-18.jpg",
              isRecommended: false,
              isInStock: true,
              sku: null,
              pointPrice: 5,
              outstock: null,
              $id: "675c7157002dc9i7f8gh",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
                {
                  name: "Fruit Popping",
                  isRequired: false,
                  maxAmount: 2,
                  type: "checkbox",
                  minAmount: 0,
                  $id: "675c6e9000419cd67g45",
                  menuOptionId: [
                    {
                      name: "Lychee Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e9000420de78h56",
                    },
                    {
                      name: "Strawberry Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e9000421ef89i67",
                    },
                    {
                      name: "Mango Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e9000422fg90j78",
                    },
                  ],
                },
              ],
            },
            {
              name: "Passion Fruit Tea",
              description: "Teh hitam dengan rasa markisa yang asam manis",
              price: 25000,
              image: null,
              isRecommended: true,
              isInStock: true,
              sku: null,
              pointPrice: null,
              outstock: null,
              $id: "675c7159002eda0j8g9hi",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
                {
                  name: "Fruit Popping",
                  isRequired: false,
                  maxAmount: 2,
                  type: "checkbox",
                  minAmount: 0,
                  $id: "675c6e9000419cd67g45",
                  menuOptionId: [
                    {
                      name: "Lychee Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e9000420de78h56",
                    },
                    {
                      name: "Strawberry Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e9000421ef89i67",
                    },
                    {
                      name: "Mango Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e9000422fg90j78",
                    },
                  ],
                },
              ],
            },
            {
              name: "Mango Tea",
              description: "Teh hitam dengan rasa mangga yang manis",
              price: 24000,
              image: null,
              isRecommended: false,
              isInStock: true,
              sku: null,
              pointPrice: null,
              outstock: null,
              $id: "675c7161002feb1k9h0ij",
              menuOptionCategory: [
                {
                  name: "Ice Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e62002d4e531ceb",
                  menuOptionId: [
                    {
                      name: "Normal",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e61003e0ef6d12b",
                    },
                    {
                      name: "Less Ice",
                      description: null,
                      price: 3000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e61003de6263ae6",
                    },
                    {
                      name: "Little Ice",
                      description: null,
                      price: 2000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e61003dcd1b67a7",
                    },
                    {
                      name: "No Ice",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e61003d552ac112",
                    },
                  ],
                },
                {
                  name: "Sugar Level",
                  isRequired: true,
                  maxAmount: 1,
                  type: "radio",
                  minAmount: null,
                  $id: "675c6e75003f1a6c9d12",
                  menuOptionId: [
                    {
                      name: "100% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 4,
                      $id: "675c6e76004012ac3d78",
                    },
                    {
                      name: "75% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 3,
                      $id: "675c6e76004011de4f23",
                    },
                    {
                      name: "50% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e76004010cd5a89",
                    },
                    {
                      name: "25% Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e7600400fae6f12",
                    },
                    {
                      name: "No Sugar",
                      description: null,
                      price: 0,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e7600400e9a7d43",
                    },
                  ],
                },
                {
                  name: "Fruit Popping",
                  isRequired: false,
                  maxAmount: 2,
                  type: "checkbox",
                  minAmount: 0,
                  $id: "675c6e9000419cd67g45",
                  menuOptionId: [
                    {
                      name: "Lychee Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 0,
                      $id: "675c6e9000420de78h56",
                    },
                    {
                      name: "Strawberry Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 1,
                      $id: "675c6e9000421ef89i67",
                    },
                    {
                      name: "Mango Popping",
                      description: "Fruit bursting boba",
                      price: 6000,
                      isInStock: true,
                      index: 2,
                      $id: "675c6e9000422fg90j78",
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  });
}
