export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "@/app/(email)/globals.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
