export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "@/app/(email)/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
